name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install --global yarn
          conda install constructor

      - name: Build
        run: |
          yarn
          yarn run build

      - name: Create App Server Installer
        run: |
          yarn create_env_installer:linux

      - name: Create App Installers
        run: |
          yarn dist:linux

      - name: Upload Debian Installer
        uses: actions/upload-artifact@v2
        with:
          name: debian-installer
          path: |
            dist/JupyterLab.deb

      - name: Upload Fedora Installer
        uses: actions/upload-artifact@v2
        with:
          name: fedora-installer
          path: |
            dist/JupyterLab.rpm
